export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const FETCHED_MOVIES = 'FETCHED_MOVIES'; 
export const MOVIES_FETCH_ERROR = 'MOVIES_FETCH_ERROR';

export const FETCHING_SIMILAR_MOVIES = 'FETCHING_SIMILAR_MOVIES';
export const FETCHED_SIMILAR_MOVIES = 'FETCHED_SIMILAR_MOVIES';
export const SIMILAR_MOVIES_FETCH_ERROR = 'SIMILAR_MOVIES_FETCH_ERROR';

export const FETCHING_GENRES = 'FETCHING_GENRES';
export const FETCHED_GENRES = 'FETCHED_GENRES';
export const GENRES_FETCH_ERROR = 'GENRES_FETCH_ERROR';

export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE';
export const REMOVE_FAVORITE_MOVIE = 'REMOVE_FAVORITE_MOVIE';
export const SAVE_FAVORITES = 'SAVE_FAVORITES';